In [1]:
import numpy as np

NumPy提供了多种创建数组的方法:
- `np.zeros()` - 创建一个所有元素都是0的数组
- `np.full()` - 创建一个所有元素都是指定值的数组
- `np.array()` - 从Python列表创建数组

In [2]:
a = np.zeros((2,3))
print(a)
b=np.full((2,3),1)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]


##### 这里我们创建了一个Python列表list1，它包含了3个子列表。
##### 然后使用np.array()将Python列表转换为NumPy数组。
##### 与普通Python列表相比，NumPy数组可以进行更高效的数值计算。
##### 并且支持更多的数学运算和数组操作。

In [3]:
list1=[[1,2],
       [3,4],
        [5,6]]
array1=np.array(list1)
print(array1)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
d=array1[1,0]
print(d)

3


In [5]:
e=array1[:,0]
print(e)

[1 3 5]


In [6]:
f=array1[2,:]
print(f)

[5 6]


NumPy提供了丰富的线性代数运算功能
以下展示一些基本的线性代数运算示例

In [7]:
matrix1 = np.array([[1, 2], 
                    [3, 4]])
matrix2 = np.array([[5, 6], 
                    [7, 8]])

矩阵点乘
矩阵对应位置相乘(Hadamard乘积)

In [8]:
print("矩阵点乘:")
print(np.dot(matrix1, matrix2))

矩阵点乘:
[[19 22]
 [43 50]]


矩阵叉乘

In [9]:
print("矩阵叉乘:")
print(np.cross(matrix1, matrix2))

矩阵叉乘:
[-4 -4]


矩阵加法

In [10]:
print("矩阵加法:")
print(matrix1 + matrix2)

矩阵加法:
[[ 6  8]
 [10 12]]


矩阵转置

In [11]:
print("矩阵转置:")
print(matrix1.T)

矩阵转置:
[[1 3]
 [2 4]]


计算行列式

In [12]:
print("行列式:")
print(np.linalg.det(matrix1))

行列式:
-2.0000000000000004


计算逆矩阵

In [13]:
print("逆矩阵:")
print(np.linalg.inv(matrix1))

逆矩阵:
[[-2.   1. ]
 [ 1.5 -0.5]]


矩阵取平均
| 操作                      | axis 值 | 聚合方向（被压缩的轴） | 结果意义   | 推荐说法  |
| ----------------------- | ------- | ---------------- | ---------- | --------- |
| `np.mean(matrix, axis=0)` | 0      | 沿 **行方向**聚合 | **每列的平均** | 对列取平均 |
| `np.mean(matrix, axis=1)` | 1      | 沿 **列方向**聚合 | **每行的平均** | 对行取平均 |

In [14]:
print("矩阵平均值:")
print(np.mean(matrix1))  # 所有元素的平均值
print(np.mean(matrix1, axis=0))  
print(np.mean(matrix1, axis=1))

矩阵平均值:
2.5
[2. 3.]
[1.5 3.5]


原来矩阵matrix1与0比较，大于0的元素不变，小于0的元素变为0

In [15]:
a=np.maximum(0,matrix1)
print("矩阵求最大值:")
print(a)

矩阵求最大值:
[[1 2]
 [3 4]]


矩阵求最小值

In [16]:
b=np.minimum(0,matrix1)
print("矩阵求最小值:")
print(b)

矩阵求最小值:
[[0 0]
 [0 0]]


留下函数每个位置最大值

In [17]:
c=np.maximum(matrix1,matrix2)
print("矩阵求最大值:")
print(c)

矩阵求最大值:
[[5 6]
 [7 8]]


一个矩阵里面求最大

In [18]:
d=np.max(matrix1)
print("一个矩阵求最大值:",d)

一个矩阵求最大值: 4
