In [51]:
# 这是一个简单的神经网络实现
# 包含3层神经元:
# 输入层: 2个神经元
# 隐藏层1: 3个神经元 
# 隐藏层2: 4个神经元
# 输出层: 2个神经元
# 使用ReLU作为激活函数

import numpy as np
def create_weights(input_size, output_size):
    """创建权重矩阵"""
    return np.random.randn(input_size, output_size)

def create_biases(size):
    """创建偏置向量"""
    return np.random.randn(size)

def activation_ReLU(sum):
    return np.maximum(0,sum)

#神经网络的层数
a11=0.9
a21=-0.4

a12=-0.8
a22=0.5

a13=-0.5
a23=0.8

a14=0.7
a24=-0.3

a15=-0.9
a25=-0.4


inputs=np.array([[a11,a21],
                [a12,a22],
                [a13,a23],
                [a14,a24],
                [a15,a25]])

#第一层神经元
weights1=create_weights(2,3)
biases1=create_biases(3)

#第二层神经元
weights2=create_weights(3,4)
biases2=create_biases(4)

#第三层神经元
weights3=create_weights(4,2)
biases3=create_biases(2)

#第一层运算
sum1=np.dot(inputs,weights1)+biases1
output1=activation_ReLU(sum1)
print("output1:")
print(output1)
print("--------------------------------")

#第二层运算
sum2=np.dot(output1,weights2)+biases2
output2=activation_ReLU(sum2)
print("output2:")
print(output2)
print("--------------------------------")

sum3=np.dot(output2,weights3)+biases3
output3=activation_ReLU(sum3)
print("output3:")
print(output3)
print("--------------------------------")



output1:
[[1.48715207 3.34887634 2.68182035]
 [0.56134052 0.         0.        ]
 [0.77765831 0.         0.        ]
 [1.37755435 2.74694872 2.19111417]
 [0.39693019 0.81299906 0.        ]]
--------------------------------
output2:
[[0.         5.5733108  0.         2.34538154]
 [0.         1.65838859 0.         0.23017112]
 [0.         2.19187199 0.         0.09630862]
 [0.         5.00277768 0.         1.91705305]
 [0.         1.12641984 0.         0.00992298]]
--------------------------------
output3:
[[0.         0.        ]
 [0.36570982 0.        ]
 [0.28951163 0.        ]
 [0.         0.        ]
 [0.66445767 0.        ]]
--------------------------------


In [54]:
#面向对象的层
class Layer:
    # 初始化函数,需要输入神经元个数和输入维度
    # self.weights和self.biases是类的属性,需要用self.来定义
    def __init__(self,n_inputs,n_neurons):
        self.weights=np.random.randn(n_inputs,n_neurons)  # weights是每个神经元的权重矩阵
        self.biases=np.random.randn(n_neurons)  # biases是每个神经元的偏置项

    # 前向传播函数,需要输入数据
    # self.sum和self.output是类的属性,需要用self.来定义
    # inputs是函数的参数,直接使用即可

    def forward(self,inputs):
        # 在Python中,当我们使用self.sum时,Python会自动为类创建一个名为sum的属性
        # 这是Python的动态特性 - 可以在运行时动态添加属性
        # 调用方法:
        # 1. 在类的其他方法中可以直接用self.sum访问
        # 2. 在类的外部可以用实例名.sum访问,比如Layer1.sum
        self.sum=np.dot(inputs,self.weights)+self.biases  # 计算加权和
        self.output=activation_ReLU(self.sum)  # 经过激活函数
        return self.output  # 返回输出结果

Layer1=Layer(2,3)
Layer2=Layer(3,4)
Layer3=Layer(4,2)
output1 =Layer1.forward(inputs)
output2=Layer2.forward(output1)
output3=Layer3.forward(output2)
print(output3)

[[0.         1.39620114]
 [2.0540452  0.        ]
 [1.48685861 0.        ]
 [0.         1.3248404 ]
 [2.62718355 0.        ]]
