In [1]:
# 这是一个简单的单层神经网络示例
# 包含:
# - 3个输入神经元(a1,a2,a3)
# - 1个输出神经元
# - 3个连接权重(w1,w2,w3)
# - 1个偏置项(b1)
# 这种结构也被称为感知器(Perceptron)

import numpy as np
# 输入层
a1=0.9
a2=0.5
a3=0.7

# 权重
w1=0.8
w2=-0.4
w3=0

# 偏置
b1=1

# 计算输出
sum1=a1*w1+a2*w2+a3*w3+b1
print(sum1)

1.52


In [2]:
# 对神经元的输出进行激活函数处理
# 这里使用ReLU(Rectified Linear Unit)激活函数
# ReLU函数的特点是:
# - 当输入x>0时,输出等于输入
# - 当输入x≤0时,输出为0
# 这种非线性的激活函数可以让神经网络学习更复杂的模式

#激活函数
def activation_ReLU(x):
    return np.maximum(0,x)

print(activation_ReLU(sum1))
print(activation_ReLU(-sum1))


1.52
0.0


In [3]:
# 使用numpy的向量化运算重写神经网络计算
# np.array()创建输入和权重的向量
# np.dot()计算向量点积,相当于加权和
# 这种向量化的写法比单独计算每个神经元更高效

# 在numpy中,一维数组默认被视为行向量
# 例如 np.array([1,2,3]) 是一个1x3的行向量
# np.dot(a,b)计算的是:a的行与b的列的点积

inputs=np.array([a1,a2,a3])

weights=np.array([[w1],[w2],[w3]])

bias=1

output=np.dot(inputs,weights)+bias

print(output)

[1.52]


In [4]:
# 下面我们将构建一个具有两个神经元的神经网络
# 每个神经元都有3个输入(a1,a2,a3)
# 每个输入都有对应的权重(w11,w21,w31和w12,w22,w32)
# 每个神经元都有一个偏置值(b11,b21)
# 这样的结构允许网络学习更复杂的特征

# 输入层
a1=-0.9
a2=-0.5
a3=-0.7

# 权重
w11=0.8
w21=-0.4
w31=0

w12=0.7
w22=-0.6
w32=0.2

b11=0.5
b21=0.5

sum1=a1*w11+a2*w21+a3*w31+b11
sum2=a1*w12+a2*w22+a3*w32+b21

print(sum1)

-0.020000000000000018


In [5]:
# 权重矩阵
# inputs 是 1x3 的行向量
# weights 应该是 3x2 的矩阵,每列对应一个神经元的权重

inputs = np.array([a1,a2,a3])  # 1x3

weights = np.array([[w11,w12],  # 3x2
                    [w21,w22],
                    [w31,w32]])

bias = np.array([b11,b21])  # 1x2

sum = np.dot(inputs,weights) + bias  # (1x3)x(3x2) + (1x2) = 1x2

print(sum)
print(activation_ReLU(sum))

[-0.02  0.03]
[0.   0.03]


In [6]:
# 在这里我们将处理多个样本(batch)的情况
# inputs 变成了一个 3x3 的矩阵,每行代表一个样本
# weights 保持 3x2 的形状不变
# bias 仍然是 1x2,但会自动广播到每个样本
# 最终输出是一个 3x2 的矩阵,每行代表一个样本的两个神经元输出

# 输入层
a11=-0.9
a21=-0.4
a31=-0.7

a12=-0.8
a22=-0.5
a32=-0.6

a13=-0.5
a23=-0.8
a33=-0.2

#batch_size=3
inputs = np.array([[a11,a21,a31],
                    [a12,a22,a32],
                    [a13,a23,a33],]) 

weights = np.array([[w11,w12],  # 3x2
                    [w21,w22],
                    [w31,w32]])

bias = np.array([b11,b21])  # 1x2

sum = np.dot(inputs,weights) + bias  

print(sum)
print("--------------------------------")
print(activation_ReLU(sum))

[[-0.06 -0.03]
 [ 0.06  0.12]
 [ 0.42  0.59]]
--------------------------------
[[0.   0.  ]
 [0.06 0.12]
 [0.42 0.59]]


In [7]:
#人工函数自动生成权重矩阵
#数据量太大的时候需要自动生成权重矩阵
def create_weights(input_size,output_size):
    return np.random.randn(input_size,output_size)

print(create_weights(3,2))

[[-7.22658719e-02  1.25637693e-02]
 [-3.28494740e-01  9.17016345e-04]
 [-1.00937677e+00  1.66992737e-01]]


In [8]:
# 对于偏置(bias),我们只需要神经元的数量,因为:
# 1. 每个神经元只需要一个偏置值
# 2. 这个偏置值会被自动广播到所有输入样本
# 3. 不同于权重矩阵需要input_size x output_size的形状,
#    偏置只需要与输出层神经元数量相同的一维向量即可

def create_biases(n_neurons): 
    return np.random.randn(n_neurons)

biases=create_biases(2)
print(biases)

[-1.53425091 -0.40318797]


In [9]:
print(inputs)
print(weights)
print(biases)
print(np.dot(inputs,weights)+biases)

[[-0.9 -0.4 -0.7]
 [-0.8 -0.5 -0.6]
 [-0.5 -0.8 -0.2]]
[[ 0.8  0.7]
 [-0.4 -0.6]
 [ 0.   0.2]]
[-1.53425091 -0.40318797]
[[-2.09425091 -0.93318797]
 [-1.97425091 -0.78318797]
 [-1.61425091 -0.31318797]]


| 含义     | 数学维度                  | 说明                   |
| ------ | --------------------- | -------------------- |
| 输入 $X$ | $m \times n$          | $m$ 个样本，每个 $n$ 维特征   |
| 权重 $W$ | $n \times p$          | $p$ 个神经元，每个连 $n$ 个输入 |
| 输出 $Z$ | $m \times p$          | 每个样本对应 $p$ 个输出       |
| 偏置 $b$ | $1 \times p$ 或 $(p,)$ | 每个神经元一个偏置，广播到每个样本    |
| 广播结果   | $m \times p$          | 和输出相同，元素级加法          |
